`**/*newline*/*.md` 中文翻译
docschina/stylelint pull request #34
Opened 2019-01-24 16:29 UTC by gucong3000

> Which issue, if any, is this issue related to?

e.g. "Closes #000" or "None, as it's a documentation fix."

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self explanatory."

2019-01-24 18:47 UTC, xiaohanxu-nick requested changes

2019-01-24 18:47 UTC, xiaohanxu-nick commented on docs/user-guide/about-rules.md
> +-   `empty-line`、`space` 和 `newline` 用于指定是否需要单个空行，单个空格，单个换行符或无空白符
句尾缺少标点符号，与其他段落不一致。

2019-01-24 18:47 UTC, xiaohanxu-nick commented on docs/user-guide/rules.md
> +-   [`at-rule-semicolon-newline-after`](../../lib/rules/at-rule-semicolon-newline-after/README.md)：在分号之后必须有换行符（可自动修复）。
建议将at-rules直译。

2019-01-24 18:47 UTC, xiaohanxu-nick commented on lib/rules/at-rule-semicolon-newline-after/README.md
> +在分号之后必须有换行符。
建议将at-rules直译。

2019-01-24 18:47 UTC, xiaohanxu-nick commented on lib/rules/block-closing-brace-newline-after/README.md
> +只要注释不包含换行符，此规则允许使用空格将行尾注释与闭括号分隔开。例如，
个人觉得译为”只要注释不包含换行符，此规则允许行尾注释，行尾注释需要与闭括号用空格分隔开。“更合适。

2019-01-24 18:47 UTC, xiaohanxu-nick commented on lib/rules/block-closing-brace-newline-after/README.md
> +忽略指定的 @规则。
与上文一致，可以直译为at-rules

2019-01-24 18:47 UTC, Xiaohanxu1996 commented on lib/rules/function-calc-no-invalid/README.md
>  -   [计算结果的类型](https://www.w3.org/TR/css-values-3/#calc-type-checking) 在对应的位置上，　该结果的类型必须是有效的。
”该结果“前多余空格。

2019-01-24 18:47 UTC, Xiaohanxu1996 commented on lib/rules/selector-list-comma-newline-after/README.md
>  End-of-line comments are allowed one space after the comma.
缺少对应翻译。

2019-01-25 03:51 UTC, gucong3000 commented on docs/user-guide/about-rules.md
> +-   `empty-line`、`space` 和 `newline` 用于指定是否需要单个空行，单个空格，单个换行符或无空白符
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#whitespace-rules

遵循了原文，原文此处就是无句号的。

2019-01-25 05:54 UTC, gucong3000 commented on docs/user-guide/rules.md
> +-   [`at-rule-semicolon-newline-after`](../../lib/rules/at-rule-semicolon-newline-after/README.md)：在分号之后必须有换行符（可自动修复）。
at-rules 的翻译来自这里：
https://developer.mozilla.org/zh-CN/docs/Web/CSS/At-rule
对于“术语”的翻译，我们应该与 MDN 之类的权威文档保持一致，而非加入个人主观意愿。以免让读者在不同的地方读到对同一个术语的不同翻译方式，从而引起误解。

2019-01-25 07:17 UTC, xiaohanxu-nick approved these changes

2019-01-25 08:24 UTC, merged