Translate the doc about processors.
docschina/stylelint pull request #38
Opened 2019-01-26 06:17 UTC by hstarorg

Translate the doc about processors.

2019-01-26 07:04 UTC, gucong3000 requested changes
- 请保留原有的 markdown 语法
- 不要改变译文的行号
- 各种术语的翻译，请与其他章节保持一致

2019-01-26 07:08 UTC, hstarorg commented
这也就意味着，采用直译的方式，是吧？不能意译。

2019-01-26 07:11 UTC, hstarorg commented
另外，请问术语列表在什么地方呢？

2019-01-26 07:55 UTC, gucong3000 commented
> 这也就意味着，采用直译的方式，是吧？不能意译。

上文中我未表述此意思，我指的是不要改变 markdown 数据结构，例如：不要把一级标题改为二级标题（第一行）；原文在第三行的段落，翻译后不要出现在第二行。

> 另外，请问术语列表在什么地方呢？

- PostCSS 和 CSS 相关术语，在[翻译指南](#39)
- 规则文档相关术语，在[构建脚本](#27)中
- 其他 stylelint 相关术语，由定义该术语或首次翻译该术语的文档的决定，如 `formatters.md` 的译者翻译了 `formatter` => `格式化程序` 后，应该同时修改其他文档中对于`formatters`这个词汇的翻译。

2019-01-26 08:07 UTC, gucong3000 requested changes

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +*以下处理器仅用于 `CLI` 和 `Node.js API` 环境，不能用于 `PostCSS` 插件。* (`PostCSS` 插件将会忽略这些处理器)
`CLI` 和 `Node.js API`的翻译，请参阅 `cli.md` 和 `node-api.md`
反引号问题同上。

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +处理器是一些社区包，允许我们从非样式表文件中抽取样式来进行 `Stylelint`.
Stylelint首字母不应大写(很遗憾与其他开源项目的命名习惯不一样)
另外反引号应该和其他文档中的使用方式保持一致(即此处不要用反引号)

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +-   [stylelint-processor-arbitrary-tags](https://github.com/mapbox/stylelint-processor-arbitrary-tags): 用于在指定的标签中执行Lint。
Lint 的翻译可参考首页，即名词linter译作“代码检查工具”，动词译作“检查”、“代码检查”、“检查...代码”

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +stylelint 已经对许多公共的非样式表文件进行了内置支持。这意味着你不再需要如下一些处理器：
common 在这个上下文中建议译作“常用”

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +-   [stylelint-processor-glamorous](https://github.com/zabute/stylelint-processor-glamorous): 用于检查[glamorous](https://github.com/paypal/glamorous)以及基于对象字面量的CSS-in-JS方案中的样式。
中英混排时请插入空格
```diff
- [stylelint-processor-glamorous](https://github.com/zabute/stylelint-processor-glamorous): 用于检查[glamorous](https://github.com/paypal/glamorous)以及基于对象字面量的CSS-in-JS方案中的样式。
+ [stylelint-processor-glamorous](https://github.com/zabute/stylelint-processor-glamorous): 用于检查 [glamorous](https://github.com/paypal/glamorous) 以及基于对象字面量的 css-in-js 方案中的样式。

2019-01-26 08:07 UTC, gucong3000 commented on docs/user-guide/processors.md
> +-   [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components): 用于检查[styled-components](https://styled-components.com)以及基于模板字符串的CSS-in-JS方案中的样
中英混排空格问题

2019-01-27 12:36 UTC, gucong3000 approved these changes

2019-01-27 12:37 UTC, merged